# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        Form.setMinimumSize(QtCore.QSize(700, 500))
        Form.setMaximumSize(QtCore.QSize(700, 500))
        self.header_label = QtWidgets.QLabel(Form)
        self.header_label.setGeometry(QtCore.QRect(0, 0, 701, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.header_label.setFont(font)
        self.header_label.setObjectName("header_label")
        self.tableWidget_coffee = QtWidgets.QTableWidget(Form)
        self.tableWidget_coffee.setGeometry(QtCore.QRect(0, 30, 701, 421))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_coffee.setFont(font)
        self.tableWidget_coffee.setObjectName("tableWidget_coffee")
        self.tableWidget_coffee.setColumnCount(0)
        self.tableWidget_coffee.setRowCount(0)
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setGeometry(QtCore.QRect(540, 460, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_edit = QtWidgets.QPushButton(Form)
        self.pushButton_edit.setGeometry(QtCore.QRect(390, 460, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_edit.setFont(font)
        self.pushButton_edit.setObjectName("pushButton_edit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Coffee info"))
        self.header_label.setText(_translate("Form", "ID, название сорта, степень обжарки, молотый/в зернах, описание вкуса, цена, объем упаковки"))
        self.pushButton_add.setText(_translate("Form", "Добавить"))
        self.pushButton_edit.setText(_translate("Form", "Изменить"))
