# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 300)
        Form.setMinimumSize(QtCore.QSize(700, 300))
        Form.setMaximumSize(QtCore.QSize(700, 300))
        Form.setSizeIncrement(QtCore.QSize(400, 0))
        self.pushButton_apply = QtWidgets.QPushButton(Form)
        self.pushButton_apply.setGeometry(QtCore.QRect(502, 247, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_apply.setFont(font)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(310, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_name.setGeometry(QtCore.QRect(310, 60, 171, 31))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_degree = QtWidgets.QLabel(Form)
        self.label_degree.setGeometry(QtCore.QRect(510, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_degree.setFont(font)
        self.label_degree.setObjectName("label_degree")
        self.lineEdit_degree = QtWidgets.QLineEdit(Form)
        self.lineEdit_degree.setGeometry(QtCore.QRect(510, 60, 171, 31))
        self.lineEdit_degree.setObjectName("lineEdit_degree")
        self.label_ground_or_whatever = QtWidgets.QLabel(Form)
        self.label_ground_or_whatever.setGeometry(QtCore.QRect(310, 210, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_ground_or_whatever.setFont(font)
        self.label_ground_or_whatever.setObjectName("label_ground_or_whatever")
        self.lineEdit_ground_or_whatever = QtWidgets.QLineEdit(Form)
        self.lineEdit_ground_or_whatever.setGeometry(QtCore.QRect(310, 250, 171, 31))
        self.lineEdit_ground_or_whatever.setObjectName("lineEdit_ground_or_whatever")
        self.label_price = QtWidgets.QLabel(Form)
        self.label_price.setGeometry(QtCore.QRect(310, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_price.setFont(font)
        self.label_price.setObjectName("label_price")
        self.lineEdit_price = QtWidgets.QLineEdit(Form)
        self.lineEdit_price.setGeometry(QtCore.QRect(310, 150, 171, 31))
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.label_volume = QtWidgets.QLabel(Form)
        self.label_volume.setGeometry(QtCore.QRect(510, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_volume.setFont(font)
        self.label_volume.setObjectName("label_volume")
        self.lineEdit_volume = QtWidgets.QLineEdit(Form)
        self.lineEdit_volume.setGeometry(QtCore.QRect(510, 150, 171, 31))
        self.lineEdit_volume.setObjectName("lineEdit_volume")
        self.label_taste = QtWidgets.QLabel(Form)
        self.label_taste.setGeometry(QtCore.QRect(10, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_taste.setFont(font)
        self.label_taste.setTextFormat(QtCore.Qt.PlainText)
        self.label_taste.setObjectName("label_taste")
        self.lineEdit_taste = QtWidgets.QLineEdit(Form)
        self.lineEdit_taste.setGeometry(QtCore.QRect(10, 60, 281, 221))
        self.lineEdit_taste.setObjectName("lineEdit_taste")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Заголовок"))
        self.pushButton_apply.setText(_translate("Form", "Применить"))
        self.label_name.setText(_translate("Form", "Название"))
        self.label_degree.setText(_translate("Form", "Обжарка"))
        self.label_ground_or_whatever.setText(_translate("Form", "Молотый или нет"))
        self.label_price.setText(_translate("Form", "Цена"))
        self.label_volume.setText(_translate("Form", "Объем"))
        self.label_taste.setText(_translate("Form", "Вкус"))
